package com.truxxkart.sellerservice_v1enums;

public enum ColorType {
  AQUA,BEIGE,BLACK,BLUE,BRONZE,BROWN,BURGUNDY,CHARCOAL,CLEAR,COFFEE,COPPER,CORAL,CREAM,ECRU,FUCHSIA,GOLD,GREEN,
  GREY,GREY_MILANGE,INDIGO,KHAKI,LAVENDER,LIME,MAGENTA,MAROON,MAUVE,METALLIC,MULTI,MUSTARD,NAVY,NUDE,OFF_WHITE,OLIVE,
  ORANGE,PEACH,PINK,PURPLE,RED,ROSE_GOLD,RUST,SEA_GREEN,SILVER,TAN,TAUPE,TEAL,TURQUOISE,VIOLET,WHITE,WINE,YELLOW
  
}
